version: "3.8"

services:
  osrm-backend:
    image: osrm-backend-alpine:v3.20.3
    container_name: osrm-backend
    volumes:
      - ./data:/data  
    ports:
      - "5000:5000"
    entrypoint:
      - sh
      - -c
      - |
        osrm-extract -p /opt/car.lua /data/colombia-241123.osm.pbf &&
        osrm-partition /data/colombia-241123.osrm &&
        osrm-customize /data/colombia-241123.osrm &&
        osrm-routed --algorithm mld /data/colombia-241123.osrm